Blog.Services.Identity/Controllers/RoleAdminController.cs
using Blog.Services.Identity.Models;
using Blog.Services.Identity.Models.ViewModels;
using IdentityModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Blog.Services.Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {

        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleAdminController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = _roleManager.Roles.ToList();

            var listViewModel = new List<RoleIndexViewModel>();

            foreach(var role in roles)
            {
                var users = await _userManager.GetUsersInRoleAsync(role.Name);

                listViewModel.Add(new RoleIndexViewModel { 
                    RoleId =  role.Id, 
                    RoleName = role.Name, 
                    Users = users 
                });
            }

            return View(listViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string roleId)
        {
            var role = _roleManager.Roles.FirstOrDefault(x => x.Id == roleId);

            if(role == null)
                return NotFound();

            var viewModel = new RoleEditViewModel
            {
                Role = role,
            };

            viewModel.Members = await _userManager.GetUsersInRoleAsync(role.Name);
            viewModel.NonMembers = _userManager.Users.ToList().Except(viewModel.Members);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleModificationViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Error", new string[] { "Роль не найдена" });

            foreach (string userId in viewModel.IdsToAdd ?? new string[] { })
            {
                var user = _userManager.Users.FirstOrDefault(x => x.Id == userId);

                var result = await _userManager.AddToRoleAsync(user, viewModel.RoleName);

                await _userManager.AddClaimAsync(user, new Claim(JwtClaimTypes.Role, viewModel.RoleName));

                if (!result.Succeeded)
                    return View("Error", result.Errors);
            }

            foreach (string userId in viewModel.IdsToDelete ?? new string[] { })
            {
                var user = _userManager.Users.FirstOrDefault(x => x.Id == userId);

                var result = await _userManager.RemoveFromRoleAsync(user, viewModel.RoleName);

                await _userManager.RemoveClaimAsync(user, new Claim(JwtClaimTypes.Role, viewModel.RoleName));

                if (!result.Succeeded)
                    return View("Error", result.Errors);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleCreateViewModel viewModel)
        {
            var role = new IdentityRole
            {
                NormalizedName = viewModel.RoleName,
                Name = viewModel.RoleName,
            };
            
            var result = await _roleManager.CreateAsync(role);

            if(!result.Succeeded)
            {
                ModelState.AddModelError(String.Empty, "Не удалось создать роль");
                return View(viewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string roleId)
        {
            var role = _roleManager.Roles.FirstOrDefault(x => x.Id == roleId);

            if (role == null)
                return NotFound();

            var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);

            var viewModel = new RoleDeleteViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name,
                Members = usersInRole.Select(user => user.UserName),
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(RoleDeleteViewModel viewModel)
        {
            var isAllUsersDeleteInRole = true;

            foreach (var user in await _userManager.GetUsersInRoleAsync(viewModel.RoleId))
            {
                var result = await _userManager.RemoveFromRoleAsync(user, viewModel.RoleId);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError(String.Empty, $"Не удалось удалить роль у пользователя {user}");
                    isAllUsersDeleteInRole = false;
                }
            }

            if(!isAllUsersDeleteInRole)
                return View(viewModel);

            var role = _roleManager.Roles.FirstOrDefault(x => x.Id == viewModel.RoleId);

            if(role == null)
            {
                ModelState.AddModelError(string.Empty, "Роль не найдена");
                return View(viewModel);
            }

            var deleteRoleResult = await _roleManager.DeleteAsync(role);

            if(deleteRoleResult.Succeeded)
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError(string.Empty, $"Не удалось удалить роль - {viewModel.RoleName}");
            return View(viewModel);
        }
    }
}

Blog.Services.Identity/Controllers/UserAdminController.cs
using Blog.Services.Identity.Models;
using Blog.Services.Identity.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Blog.Services.Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public UserAdminController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = new List<UserIndexViewModel>();

            foreach(var user in _userManager.Users)
                viewModel.Add(new UserIndexViewModel
                {
                    User = user,
                    Roles = await _userManager.GetRolesAsync(user),
                });

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == userId);

            if (user == null)
                return NotFound();

            var viewModel = new UserEditViewModel 
            { 
                UserId = userId,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditViewModel viewModel)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == viewModel.UserId);

            if (user == null)
                return NotFound();

            user.UserName = viewModel.UserName;
            user.FirstName = viewModel.FirstName;
            user.LastName = viewModel.LastName;

            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError(string.Empty, "Не удалось обновить информацию о пользователе");
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string userId)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == userId);

            if (user == null)
                return NotFound();

            var viewModel = new UserDeleteViewModel
            {
                UserId = userId,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteViewModel viewModel)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == viewModel.UserId);

            if (user == null)
                return NotFound();

            var result = await _userManager.DeleteAsync(user);

            if (result.Succeeded)
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError(string.Empty, "Не удалось удалить пользователя");
            return View(viewModel);
        }
    }
}

Blog.Services.Identity/Views/Shared/_Layout.cshtml
@using Blog.Services.Identity

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityInBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    @if(User.IsInRole(Configuration.Admin))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogIdentity</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text" asp-area="" asp-controller="RoleAdmin" asp-action="Index">Роли</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text" asp-area="" asp-controller="UserAdmin" asp-action="Index">Пользователи</a>
                            </li>
                        </ul>
                    </div>

                    <partial name="_LoginPartial" />
                </div>
            </nav>
        </header>
    }


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>